baseURL: "http://localhost/"
languageCode: "en-us"
title: "xtreamwayz"

enableGitInfo: true
enableInlineShortcodes: true
googleAnalytics: UA-151173516-1

pygmentsCodeFences: true
pygmentsOptions: linenos=table
pygmentsUseClasses: true
pygmentsUseClassic: false

disableKinds:
- taxonomy
- taxonomyTerm
