hugoVersion:
  extended: true
  min: '0.69.0'

imports:
  - path: 'github.com/xtreamwayz/psr-container-messenger'
    mounts:
      - source: 'docs'
        target: 'content/psr-container-messenger'
  - path: 'github.com/xtreamwayz/html-form-validator'
    mounts:
      - source: 'docs'
        target: 'content/html-form-validator'
  - path: 'github.com/xtreamwayz/mezzio-console'
    mounts:
      - source: 'docs'
        target: 'content/mezzio-console'
