hugoVersion:
  extended: true
  min: "0.59.0"

imports:
  - path: "github.com/xtreamwayz/devops"
    mounts:
      - source: "docs"
        target: "content/devops"
  - path: "github.com/xtreamwayz/expressive-console"
    mounts:
      - source: "docs"
        target: "content/expressive-console"
