hugoVersion:
  extended: true
  min: "0.59.0"

imports:
  - path: "github.com/xtreamwayz/psr-container-messenger"
    mounts:
      - source: "docs"
        target: "content/psr-container-messenger"
  - path: "github.com/xtreamwayz/html-form-validator"
    mounts:
      - source: "docs"
        target: "content/html-form-validator"
  - path: "github.com/xtreamwayz/devops"
    mounts:
      - source: "docs"
        target: "content/devops"
  - path: "github.com/xtreamwayz/expressive-console"
    mounts:
      - source: "docs"
        target: "content/expressive-console"
