name: github pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Build site
        run: |
          docker run --rm -it --volume $(pwd):/src xtreamwayz/hugo npm install
          docker run --rm -it --volume $(pwd):/src xtreamwayz/hugo hugo mod init website
          docker run --rm -it --volume $(pwd):/src xtreamwayz/hugo hugo --gc --minify --enableGitInfo --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
