name: github pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
          run: npm install

      - uses: jakejarvis/hugo-build-action@master
          with:
            args: --gc --minify -b https://xtreamwayz.github.io/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
