name: github-pages

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: docker://iswai/docs:latest
      with:
        args: 'build'

    - name: Deploy
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.ISWAI_BOT }}
        PUBLISH_REPOSITORY: iswai/iswai.github.io
        PUBLISH_BRANCH: master
      run: wget -O - https://raw.githubusercontent.com/iswai/docs-sdk/master/actions/gh-pages-deploy | bash
